/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Quality */
        get: operations["data_quality_api_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Imports */
        get: operations["imports_api_data_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Re-import from the configured provider in the background (idempotent upserts).
         *
         *     Live providers fetch from 10 sessions before the latest stored session, so late
         *     corrections are picked up; the demo fixture is simply re-imported.
         */
        post: operations["refresh_api_data_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universe */
        get: operations["universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Detail */
        get: operations["stock_detail_api_universe__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Command Center */
        get: operations["command_center_api_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_api_portfolio_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paper Init */
        post: operations["paper_init_api_paper_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paper Advance */
        post: operations["paper_advance_api_paper_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paper Reset */
        post: operations["paper_reset_api_paper_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paper Config */
        get: operations["paper_config_api_paper_config_get"];
        /** Paper Config Update */
        put: operations["paper_config_update_api_paper_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/seed-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reseed Demo
         * @description Recreate the demo portfolio (archiving the current one). Demo mode only.
         */
        post: operations["reseed_demo_api_paper_seed_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rebalance/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans */
        get: operations["plans_api_rebalance_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rebalance/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current */
        get: operations["current_api_rebalance_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rebalance/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan Detail */
        get: operations["plan_detail_api_rebalance_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rebalance/plans/{plan_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply
         * @description Apply the plan to the INTERNAL VIRTUAL PORTFOLIO ONLY. Nothing is sent to any broker.
         */
        post: operations["apply_api_rebalance_plans__plan_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rebalance/plans/{plan_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip */
        post: operations["skip_api_rebalance_plans__plan_id__skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Defaults */
        get: operations["defaults_api_research_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_research_runs_get"];
        put?: never;
        /** Launch */
        post: operations["launch_api_research_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_research_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Series */
        get: operations["run_series_api_research_runs__run_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Monthly */
        get: operations["run_monthly_api_research_runs__run_id__monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Trades */
        get: operations["run_trades_api_research_runs__run_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}/rebalances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Rebalances */
        get: operations["run_rebalances_api_research_runs__run_id__rebalances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders */
        get: operations["orders_api_ledger_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fills */
        get: operations["fills_api_ledger_fills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cash */
        get: operations["cash_api_ledger_cash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_ledger_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/reproducibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reproducibility */
        get: operations["reproducibility_api_ledger_reproducibility_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvanceResponse */
        AdvanceResponse: {
            /** Processed */
            processed: string[];
            /** Processed Count */
            processed_count: number;
            /** As Of */
            as_of: string;
            /** Stopped Reason */
            stopped_reason: string;
            /** Stopped Explanation */
            stopped_explanation: string;
            /** Pending Plan Id */
            pending_plan_id: number | null;
        };
        /** CashPage */
        CashPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["CashTx"][];
        };
        /** CashTx */
        CashTx: {
            /** Id */
            id: number;
            /** Session */
            session: string;
            /** Kind */
            kind: string;
            /** Symbol */
            symbol: string | null;
            /** Amount */
            amount: number;
            /** Balance After */
            balance_after: number;
            /** Fill Id */
            fill_id: number | null;
            /** Note */
            note: string | null;
            /** Created At */
            created_at: string;
        };
        /** CommandCenter */
        CommandCenter: {
            /** Data Label */
            data_label: string;
            portfolio: components["schemas"]["PortfolioMeta"] | null;
            /** Valuation Session */
            valuation_session: string | null;
            /** Nav */
            nav: number | null;
            /** Cash */
            cash: number | null;
            /** Invested */
            invested: number | null;
            /** Positions */
            positions: number;
            /** Daily Return */
            daily_return: number | null;
            /** Daily Pnl */
            daily_pnl: number | null;
            /** Inception Return */
            inception_return: number | null;
            /** Gross Inception Return */
            gross_inception_return: number | null;
            /** Benchmark Symbol */
            benchmark_symbol: string | null;
            /** Benchmark Return Basis */
            benchmark_return_basis: string | null;
            /** Benchmark Inception Return */
            benchmark_inception_return: number | null;
            /** Return Difference */
            return_difference: number | null;
            /** Drawdown */
            drawdown: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Mode */
            mode?: string | null;
            /** Long Gross */
            long_gross?: number | null;
            /** Short Gross */
            short_gross?: number | null;
            /** Net Exposure */
            net_exposure?: number | null;
            next_rebalance: components["schemas"]["NextRebalance"];
            /** Nav Series */
            nav_series: components["schemas"]["NavPoint"][];
            /** Top Movers */
            top_movers: components["schemas"]["Mover"][];
            /** Recent Fills */
            recent_fills: components["schemas"]["FillModel"][];
            /** Alerts */
            alerts: components["schemas"]["EventModel"][];
            /** Data Is Stale */
            data_is_stale: boolean;
            /** Data Stale Reason */
            data_stale_reason: string | null;
            /** Data End */
            data_end: string | null;
        };
        /** Concentration */
        Concentration: {
            /** Top5 Weight */
            top5_weight: number;
            /** Top10 Weight */
            top10_weight: number;
            /** Largest Symbol */
            largest_symbol: string | null;
            /** Largest Weight */
            largest_weight: number;
            /** Hhi */
            hhi: number;
            /** Effective N */
            effective_n: number | null;
        };
        /** CorporateActionModel */
        CorporateActionModel: {
            /** Ex Date */
            ex_date: string;
            /** Action Type */
            action_type: string;
            /** Ratio */
            ratio: number | null;
            /** Amount */
            amount: number | null;
        };
        /** DataImport */
        DataImport: {
            /** Id */
            id: number;
            /** Provider */
            provider: string;
            /** Feed */
            feed: string | null;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Requested Start */
            requested_start: string | null;
            /** Requested End */
            requested_end: string | null;
            /** Coverage Start */
            coverage_start: string | null;
            /** Coverage End */
            coverage_end: string | null;
            /** Symbols Requested */
            symbols_requested: number | null;
            /** Symbols Loaded */
            symbols_loaded: number | null;
            /** Bars Loaded */
            bars_loaded: number | null;
            /** Actions Loaded */
            actions_loaded: number | null;
            /** Warnings */
            warnings: string[];
            /** Error */
            error: string | null;
        };
        /** DataQuality */
        DataQuality: {
            provider: components["schemas"]["ProviderInfoModel"];
            /** Has Data */
            has_data: boolean;
            latest_import: components["schemas"]["DataImport"] | null;
            latest_successful_import: components["schemas"]["DataImport"] | null;
            /** Coverage Start */
            coverage_start: string | null;
            /** Coverage End */
            coverage_end: string | null;
            /** Expected Latest Session */
            expected_latest_session: string | null;
            /** Is Stale */
            is_stale: boolean;
            /** Stale Reason */
            stale_reason: string | null;
            /** Instruments */
            instruments: number;
            /** Universe Count */
            universe_count: number;
            /** Eligible Count */
            eligible_count?: number | null;
            /** Total Bars */
            total_bars?: number | null;
            /** Missing Bars */
            missing_bars: number;
            /** Missing Opens */
            missing_opens: number;
            /** Stale Symbols */
            stale_symbols: components["schemas"]["StaleSymbol"][];
            /** Latest Session Coverage */
            latest_session_coverage: number;
            /** Benchmark Symbol */
            benchmark_symbol?: string | null;
            /** Warnings */
            warnings: components["schemas"]["QualityWarning"][];
            /** Generated At */
            generated_at: string;
        };
        /** EventModel */
        EventModel: {
            /** Id */
            id: number;
            /** Ts */
            ts: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Category */
            category: string;
            /** Message */
            message: string;
            /** Portfolio Id */
            portfolio_id: number | null;
            /** Run Id */
            run_id: number | null;
            /** Session */
            session: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** EventsPage */
        EventsPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["EventModel"][];
        };
        /** FillModel */
        FillModel: {
            /** Id */
            id: number;
            /** Session */
            session: string;
            /** Symbol */
            symbol: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Shares */
            shares: number;
            /** Ref Price */
            ref_price: number;
            /** Fill Price */
            fill_price: number;
            /** Gross Value */
            gross_value: number;
            /** Slippage Cost */
            slippage_cost: number;
            /** Commission */
            commission: number;
            /** Plan Id */
            plan_id?: number | null;
            /** Order Id */
            order_id?: number | null;
            /** Reason */
            reason?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Position Effect */
            position_effect?: string | null;
        };
        /** FillsPage */
        FillsPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["FillModel"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MarketClock */
        MarketClock: {
            /** Now Utc */
            now_utc: string;
            /** Now New York */
            now_new_york: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed" | "pre_open" | "after_close";
            /** Session Today */
            session_today: string | null;
            /** Next Open Utc */
            next_open_utc: string | null;
            /** Next Close Utc */
            next_close_utc: string | null;
            /** Calendar */
            calendar: string;
            /** Source */
            source: string;
        };
        /** MonthlyReturn */
        MonthlyReturn: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Strategy */
            strategy: number;
            /** Benchmark */
            benchmark: number | null;
        };
        /** Mover */
        Mover: {
            /** Symbol */
            symbol: string;
            /** Return 1D */
            return_1d: number | null;
            /** Pnl 1D */
            pnl_1d: number;
            /** Weight */
            weight: number;
        };
        /** NavPoint */
        NavPoint: {
            /** Session */
            session: string;
            /** Nav */
            nav: number;
            /** Gross Nav */
            gross_nav: number;
            /** Cash */
            cash: number;
            /** Benchmark Nav */
            benchmark_nav: number | null;
            /** Drawdown */
            drawdown: number;
        };
        /** NextRebalance */
        NextRebalance: {
            /** Signal Session */
            signal_session: string | null;
            /** Fill Session */
            fill_session: string | null;
            /** Pending Plan Id */
            pending_plan_id: number | null;
            /** Pending Plan Status */
            pending_plan_status: string | null;
            /** Blocked Reason */
            blocked_reason: string | null;
        };
        /** OrderModel */
        OrderModel: {
            /** Id */
            id: number;
            /** Plan Id */
            plan_id: number | null;
            /**
             * Origin
             * @default plan
             */
            origin: string;
            /** Trigger Session */
            trigger_session?: string | null;
            /** Symbol */
            symbol: string;
            /** Intended Side */
            intended_side: string;
            /** Target Weight */
            target_weight: number;
            /** Est Shares */
            est_shares: number;
            /** Fill Session */
            fill_session: string;
            /** Status */
            status: string;
            /** Status Reason */
            status_reason: string | null;
            /** Filled Shares */
            filled_shares: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** OrdersPage */
        OrdersPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["OrderModel"][];
        };
        /** PaperAdvanceRequest */
        PaperAdvanceRequest: {
            /**
             * Until
             * @description Last session to process (default: latest stored data)
             */
            until?: string | null;
            /** Max Sessions */
            max_sessions?: number | null;
        };
        /** PaperConfigResponse */
        PaperConfigResponse: {
            /** Config Id */
            config_id: number;
            config: components["schemas"]["StrategyConfig"];
            /** History */
            history: {
                [key: string]: unknown;
            }[];
        };
        /** PaperInitRequest */
        PaperInitRequest: {
            /**
             * Inception Session
             * @description Session at whose close cash is funded; default latest data session
             */
            inception_session?: string | null;
            config?: components["schemas"]["StrategyConfig"] | null;
            /** Name */
            name?: string | null;
        };
        /** PlanDetail */
        PlanDetail: {
            /** Id */
            id: number;
            /** Signal Session */
            signal_session: string;
            /** Fill Session */
            fill_session: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "applied" | "executed" | "skipped" | "blocked";
            /** Block Reason */
            block_reason: string | null;
            /** Created At */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Executed At */
            executed_at: string | null;
            /** Selected Count */
            selected_count: number;
            /** Est Turnover */
            est_turnover: number | null;
            /** Realized Turnover */
            realized_turnover: number | null;
            /** Data Label */
            data_label: string;
            /** Data Version */
            data_version: string;
            config: components["schemas"]["StrategyConfig"];
            /** Estimate */
            estimate: {
                [key: string]: unknown;
            };
            /** Execution */
            execution: {
                [key: string]: unknown;
            } | null;
            /** Checks */
            checks: components["schemas"]["RuleCheck"][];
            /** Orders */
            orders: components["schemas"]["PlanOrderModel"][];
            /** Targets */
            targets: components["schemas"]["PlanTarget"][];
            /** Fills */
            fills: components["schemas"]["FillModel"][];
            /** Can Apply */
            can_apply: boolean;
            /** Apply Disabled Reason */
            apply_disabled_reason: string | null;
            /** Portfolio As Of */
            portfolio_as_of: string;
        };
        /** PlanOrderModel */
        PlanOrderModel: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Current Shares */
            current_shares: number;
            /** Target Shares */
            target_shares: number;
            /** Est Shares */
            est_shares: number;
            /** Est Price */
            est_price: number;
            /** Est Value */
            est_value: number;
            /** Est Cost */
            est_cost: number;
            /** Current Weight */
            current_weight: number;
            /** Target Weight */
            target_weight: number;
            /** Note */
            note: string | null;
            /** Order Status */
            order_status?: string | null;
            /** Filled Shares */
            filled_shares?: number | null;
            /** Order Reason */
            order_reason?: string | null;
        };
        /** PlanSummary */
        PlanSummary: {
            /** Id */
            id: number;
            /** Signal Session */
            signal_session: string;
            /** Fill Session */
            fill_session: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "applied" | "executed" | "skipped" | "blocked";
            /** Block Reason */
            block_reason: string | null;
            /** Created At */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Executed At */
            executed_at: string | null;
            /** Selected Count */
            selected_count: number;
            /** Est Turnover */
            est_turnover: number | null;
            /** Realized Turnover */
            realized_turnover: number | null;
        };
        /** PlanTarget */
        PlanTarget: {
            /** Symbol */
            symbol: string;
            /** Rank */
            rank: number;
            /** Momentum */
            momentum: number;
            /** Close Raw */
            close_raw: number;
            /** Adv20 */
            adv20: number;
            /** Target Weight */
            target_weight: number;
            /** Current Weight */
            current_weight: number;
            /** Side */
            side?: string | null;
            /** Vol */
            vol?: number | null;
            /** Beta */
            beta?: number | null;
            /** Percentile */
            percentile?: number | null;
        };
        /** PortfolioMeta */
        PortfolioMeta: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
            /** Initial Capital */
            initial_capital: number;
            /** Cash */
            cash: number;
            /** Inception Session */
            inception_session: string;
            /** As Of Session */
            as_of_session: string;
            /** Config Id */
            config_id: number;
            /** Cum Costs */
            cum_costs: number;
            /** Created At */
            created_at: string;
            /** Notes */
            notes: string | null;
        };
        /** PositionRow */
        PositionRow: {
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Name */
            name: string | null;
            /** Sector */
            sector: string | null;
            /** Shares */
            shares: number;
            /** Mark Price */
            mark_price: number;
            /** Mark Session */
            mark_session: string;
            /** Stale Mark */
            stale_mark: boolean;
            /** Market Value */
            market_value: number;
            /** Weight */
            weight: number;
            /** Target Weight */
            target_weight: number | null;
            /** Drift */
            drift: number | null;
            /** Cost Basis */
            cost_basis: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /** Unrealized Pct */
            unrealized_pct: number | null;
            /**
             * Contribution
             * @description Unrealized P&L / NAV
             */
            contribution: number;
            /** Return 1D */
            return_1d: number | null;
            /** Opened Session */
            opened_session: string | null;
        };
        /** PositionsResponse */
        PositionsResponse: {
            /** Data Label */
            data_label: string;
            /** Valuation Session */
            valuation_session: string | null;
            /** Valuation Note */
            valuation_note: string;
            /** Nav */
            nav: number;
            /** Cash */
            cash: number;
            /** Cash Weight */
            cash_weight: number;
            /** Rows */
            rows: components["schemas"]["PositionRow"][];
            /** Long Gross */
            long_gross: number;
            /** Short Gross */
            short_gross: number;
            /** Net Exposure */
            net_exposure: number;
            /** Mode */
            mode: string;
            /** Sector Exposure */
            sector_exposure: components["schemas"]["SectorExposure"][] | null;
            /** Sector Note */
            sector_note: string;
            concentration: components["schemas"]["Concentration"];
            /** Plan Signal Session */
            plan_signal_session: string | null;
        };
        /** PricePoint */
        PricePoint: {
            /** Session */
            session: string;
            /** Open */
            open: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Close */
            close: number | null;
            /** Volume */
            volume: number | null;
            /** Tr Index */
            tr_index: number | null;
        };
        /** ProviderInfoModel */
        ProviderInfoModel: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Feed */
            feed: string;
            /** Data Label */
            data_label: string;
            /** Is Demo */
            is_demo: boolean;
            /** Benchmark Symbol */
            benchmark_symbol: string;
            /** Benchmark Return Basis */
            benchmark_return_basis: string;
            /** Point In Time Universe */
            point_in_time_universe: boolean;
            /** Coverage Note */
            coverage_note: string;
            /** Entitlement Note */
            entitlement_note: string;
            /** Adjustment Note */
            adjustment_note: string;
            /** Survivorship Note */
            survivorship_note: string;
            /** Requires Key */
            requires_key: boolean;
        };
        /** QualityWarning */
        QualityWarning: {
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Started */
            started: boolean;
            /** Message */
            message: string;
        };
        /** Reproducibility */
        Reproducibility: {
            /** App Version */
            app_version: string;
            /** Git Commit */
            git_commit: string | null;
            /** Python */
            python: string;
            /** Packages */
            packages: {
                [key: string]: string;
            };
            /** Database Path */
            database_path: string;
            /** Schema Migrations */
            schema_migrations: {
                [key: string]: unknown;
            }[];
            /** Provider */
            provider: string;
            /** Data Version */
            data_version: string | null;
            /** Portfolio Configs */
            portfolio_configs: {
                [key: string]: unknown;
            }[];
            /** Plan Data Versions */
            plan_data_versions: {
                [key: string]: unknown;
            }[];
        };
        /** ResearchDefaults */
        ResearchDefaults: {
            /** Data Label */
            data_label: string;
            config: components["schemas"]["StrategyConfig"];
            /** Earliest Start */
            earliest_start: string;
            /** Latest End */
            latest_end: string;
            /** Benchmark Symbol */
            benchmark_symbol: string | null;
            /** Survivorship Warning */
            survivorship_warning: string | null;
        };
        /** RuleCheck */
        RuleCheck: {
            /** Rule */
            rule: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /** Progress */
            progress: number;
            /** Progress Note */
            progress_note: string | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
            /** Provider */
            provider: string;
            /** Data Label */
            data_label: string;
            /** Data Version */
            data_version: string;
            config: components["schemas"]["StrategyConfig"];
            /** Headline */
            headline: {
                [key: string]: unknown;
            } | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            } | null;
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            }[];
            /** Warnings */
            warnings: string[];
            /** Repro */
            repro: {
                [key: string]: unknown;
            } | null;
        };
        /** RunRebalance */
        RunRebalance: {
            /** Id */
            id: number;
            /** Signal Session */
            signal_session: string;
            /** Fill Session */
            fill_session: string | null;
            /** Status */
            status: string;
            /** Universe Count */
            universe_count: number;
            /** Eligible Count */
            eligible_count: number;
            /** Selected Count */
            selected_count: number;
            /** Nav At Open */
            nav_at_open: number | null;
            /** Turnover */
            turnover: number | null;
            /** Slippage Cost */
            slippage_cost: number | null;
            /** Commission */
            commission: number | null;
            /** Cash After */
            cash_after: number | null;
            /** Unfilled */
            unfilled: {
                [key: string]: unknown;
            }[];
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            } | null;
        };
        /** RunRequest */
        RunRequest: {
            config: components["schemas"]["StrategyConfig"];
            /** Name */
            name?: string | null;
        };
        /** RunSeriesPoint */
        RunSeriesPoint: {
            /** Session */
            session: string;
            /** Nav */
            nav: number;
            /** Gross Nav */
            gross_nav: number;
            /** Benchmark Nav */
            benchmark_nav: number | null;
            /** Drawdown */
            drawdown: number;
            /** Benchmark Drawdown */
            benchmark_drawdown: number | null;
            /** Cash Weight */
            cash_weight: number;
            /** Positions */
            positions: number;
            /** Long Gross */
            long_gross?: number | null;
            /** Short Gross */
            short_gross?: number | null;
            /** Net Exposure */
            net_exposure?: number | null;
            /** Rolling Return */
            rolling_return: number | null;
            /** Rolling Vol */
            rolling_vol: number | null;
            /** Rolling Bench Return */
            rolling_bench_return: number | null;
            /** Rolling Difference */
            rolling_difference: number | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /** Progress */
            progress: number;
            /** Progress Note */
            progress_note: string | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
            /** Provider */
            provider: string;
            /** Data Label */
            data_label: string;
            /** Data Version */
            data_version: string;
            config: components["schemas"]["StrategyConfig"];
            /** Headline */
            headline: {
                [key: string]: unknown;
            } | null;
        };
        /** SectorExposure */
        SectorExposure: {
            /** Sector */
            sector: string;
            /** Weight */
            weight: number;
            /**
             * Long Weight
             * @default 0
             */
            long_weight: number;
            /**
             * Short Weight
             * @default 0
             */
            short_weight: number;
            /** Positions */
            positions: number;
        };
        /** SignalInputs */
        SignalInputs: {
            /** Signal Session */
            signal_session: string;
            /** Session T21 */
            session_t21: string | null;
            /** Session T252 */
            session_t252: string | null;
            /** Close T */
            close_t: number | null;
            /** Close T21 Raw */
            close_t21_raw: number | null;
            /** Close T252 Raw */
            close_t252_raw: number | null;
            /** Tr T21 */
            tr_t21: number | null;
            /** Tr T252 */
            tr_t252: number | null;
            /** Momentum */
            momentum: number | null;
            /** Adv20 */
            adv20: number | null;
            /** Valid History */
            valid_history: number;
            /** Eligible */
            eligible: boolean;
            /** Reason */
            reason: string;
            /** Reason Text */
            reason_text: string;
            /** Rank */
            rank: number | null;
            /** Formula */
            formula: string;
        };
        /** SkipRequest */
        SkipRequest: {
            /** Note */
            note?: string | null;
        };
        /** StaleSymbol */
        StaleSymbol: {
            /** Symbol */
            symbol: string;
            /** Last Bar */
            last_bar: string;
        };
        /** StockDetail */
        StockDetail: {
            /** Data Label */
            data_label: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string | null;
            /** Sector */
            sector: string | null;
            /** Sector Source */
            sector_source: string | null;
            /** Asset Type */
            asset_type: string;
            /** Asset Type Source */
            asset_type_source: string | null;
            /** Exchange */
            exchange: string | null;
            /** List Date */
            list_date: string | null;
            /** Delist Date */
            delist_date: string | null;
            signal: components["schemas"]["SignalInputs"];
            /** Prices */
            prices: components["schemas"]["PricePoint"][];
            /** Corporate Actions */
            corporate_actions: components["schemas"]["CorporateActionModel"][];
            /** Position Shares */
            position_shares: number;
        };
        /**
         * StrategyConfig
         * @description All tunable inputs of the 12-1 momentum strategy.
         *
         *     mode="long_only"  -> v1: top_n winners, equal weight, cash-funded, no shorts.
         *     mode="long_short" -> v2: decile winners long / decile losers short with a
         *         rank buffer, inverse-volatility weights with per-name caps, beta-neutral
         *         books scaled to a volatility target within gross limits, a momentum-crash
         *         guard, a $10 short price floor, borrow fees and a short stop-loss.
         *     Every backtest run and every paper-portfolio configuration version stores the
         *     full JSON of this model.
         */
        StrategyConfig: {
            /**
             * Mode
             * @description Strategy variant
             * @default long_short
             * @enum {string}
             */
            mode: "long_only" | "long_short";
            /**
             * Initial Capital
             * @description Starting virtual cash, USD
             * @default 100000
             */
            initial_capital: number;
            /**
             * Top N
             * @description Number of top-ranked eligible stocks to hold
             * @default 50
             */
            top_n: number;
            /**
             * Lookback Sessions
             * @description Older momentum anchor: sessions before signal
             * @default 252
             */
            lookback_sessions: number;
            /**
             * Skip Sessions
             * @description Recent anchor: sessions before signal (skip month)
             * @default 21
             */
            skip_sessions: number;
            /**
             * Min History Sessions
             * @description Valid bars required before the signal session
             * @default 252
             */
            min_history_sessions: number;
            /**
             * Min Price
             * @description Raw (unadjusted) close at the signal session must exceed this, USD
             * @default 5
             */
            min_price: number;
            /**
             * Adv Window
             * @description Sessions in the average dollar-volume window
             * @default 20
             */
            adv_window: number;
            /**
             * Min Adv Usd
             * @description Minimum trailing average daily dollar volume, USD
             * @default 5000000
             */
            min_adv_usd: number;
            /**
             * Slippage Bps
             * @description Assumed adverse slippage vs. the open, basis points
             * @default 10
             */
            slippage_bps: number;
            /**
             * Commission Per Order
             * @description Assumed flat commission per fill, USD
             * @default 0
             */
            commission_per_order: number;
            /**
             * Commission Bps
             * @description Assumed commission as bps of traded value
             * @default 0
             */
            commission_bps: number;
            /**
             * Min Session Coverage
             * @description Share of the point-in-time universe that must have a bar at the signal session; otherwise the rebalance is blocked
             * @default 0.9
             */
            min_session_coverage: number;
            /**
             * Long Pct
             * @description Enter longs from the top fraction of eligible stocks
             * @default 0.1
             */
            long_pct: number;
            /**
             * Short Pct
             * @description Enter shorts from the bottom fraction of eligible stocks
             * @default 0.1
             */
            short_pct: number;
            /**
             * Min Names Per Side
             * @description Minimum names per book (filled by next ranks)
             * @default 50
             */
            min_names_per_side: number;
            /**
             * Max Names Per Side
             * @description Maximum names per book (best ranks kept)
             * @default 100
             */
            max_names_per_side: number;
            /**
             * Buffer Exit Pct
             * @description Buffer: a held long stays while in the top fraction, a held short while in the bottom fraction
             * @default 0.3
             */
            buffer_exit_pct: number;
            /**
             * Vol Lookback Sessions
             * @description Realized-vol window (sessions), ~6 months
             * @default 126
             */
            vol_lookback_sessions: number;
            /**
             * Beta Lookback Sessions
             * @description Beta estimation window (sessions)
             * @default 252
             */
            beta_lookback_sessions: number;
            /**
             * Beta Shrink
             * @description Beta shrinkage toward 1.0 (Vasicek-style)
             * @default 0.33
             */
            beta_shrink: number;
            /**
             * Target Vol
             * @description Annualized portfolio volatility target (ex-ante, trailing)
             * @default 0.1
             */
            target_vol: number;
            /**
             * Min Side Gross
             * @description Minimum gross per side, fraction of NAV
             * @default 0.5
             */
            min_side_gross: number;
            /**
             * Max Side Gross
             * @description Maximum gross per side, fraction of NAV
             * @default 0.75
             */
            max_side_gross: number;
            /**
             * Max Total Gross
             * @description Cap on long + short gross, fraction of NAV
             * @default 1.5
             */
            max_total_gross: number;
            /**
             * Max Long Weight
             * @description Per-name cap on longs, fraction of NAV
             * @default 0.02
             */
            max_long_weight: number;
            /**
             * Max Short Weight
             * @description Per-name cap on shorts, fraction of NAV
             * @default 0.01
             */
            max_short_weight: number;
            /**
             * Short Min Price
             * @description Raw close must exceed this to be shorted, USD
             * @default 10
             */
            short_min_price: number;
            /**
             * Borrow Fee Annual
             * @description Assumed borrow cost on short market value, per year
             * @default 0.005
             */
            borrow_fee_annual: number;
            /**
             * Short Stop Loss
             * @description Cover a short when its close is this fraction above entry (fill next open)
             * @default 0.5
             */
            short_stop_loss: number | null;
            /**
             * Crash Guard
             * @description Scale down the short book in bear/high-vol markets
             * @default true
             */
            crash_guard: boolean;
            /**
             * Crash Market Lookback Sessions
             * @description Market return window (~24 months)
             * @default 504
             */
            crash_market_lookback_sessions: number;
            /**
             * Crash Market Vol Threshold
             * @description Market 6-month realized vol deemed 'high'
             * @default 0.2
             */
            crash_market_vol_threshold: number;
            /**
             * Crash Short Scale
             * @description Short-book multiplier when the crash guard is on
             * @default 0.5
             */
            crash_short_scale: number;
            /**
             * Start Date
             * @description Backtest start (ISO date); ignored by the paper ledger
             */
            start_date?: string | null;
            /**
             * End Date
             * @description Backtest end (ISO date); ignored by the paper ledger
             */
            end_date?: string | null;
            /**
             * Benchmark Symbol
             * @description Benchmark; default = provider's SPY (or demo stand-in)
             */
            benchmark_symbol?: string | null;
        };
        /** SystemStatus */
        SystemStatus: {
            /** App Version */
            app_version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "demo" | "live";
            /** Data Label */
            data_label: string;
            provider: components["schemas"]["ProviderInfoModel"] | null;
            /** Provider Error */
            provider_error: string | null;
            market_clock: components["schemas"]["MarketClock"];
            /** Data Version */
            data_version: string | null;
            /** Data Start */
            data_start: string | null;
            /** Data End */
            data_end: string | null;
            /** Has Portfolio */
            has_portfolio: boolean;
            /** Portfolio As Of */
            portfolio_as_of: string | null;
            /** Server Time Utc */
            server_time_utc: string;
            /** Bind Host */
            bind_host: string;
        };
        /** UniverseResponse */
        UniverseResponse: {
            /** Data Label */
            data_label: string;
            /** Signal Session */
            signal_session: string;
            /** Is Month End */
            is_month_end: boolean;
            /** Basis Note */
            basis_note: string;
            /** Plan Signal Session */
            plan_signal_session: string | null;
            /** Portfolio As Of */
            portfolio_as_of: string | null;
            config: components["schemas"]["StrategyConfig"];
            /** Universe Count */
            universe_count: number;
            /** Eligible Count */
            eligible_count: number;
            /** Selected Count */
            selected_count: number;
            /** Coverage */
            coverage: number;
            /** Blocked Reason */
            blocked_reason: string | null;
            /** Reason Counts */
            reason_counts: {
                [key: string]: number;
            };
            /**
             * Diagnostics
             * @default {}
             */
            diagnostics: {
                [key: string]: unknown;
            };
            /** Rows */
            rows: components["schemas"]["UniverseRow"][];
        };
        /** UniverseRow */
        UniverseRow: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string | null;
            /** Sector */
            sector: string | null;
            /** Asset Type */
            asset_type: string;
            /** Close Raw */
            close_raw: number | null;
            /** Adv20 */
            adv20: number | null;
            /** Momentum */
            momentum: number | null;
            /** Rank */
            rank: number | null;
            /** Eligible */
            eligible: boolean;
            /** Reason */
            reason: string;
            /** Reason Text */
            reason_text: string;
            /** Selected */
            selected: boolean;
            /**
             * Side
             * @description long | short | None in this live ranking
             */
            side?: string | null;
            /** Percentile */
            percentile?: number | null;
            /** Vol */
            vol?: number | null;
            /** Beta */
            beta?: number | null;
            /**
             * Model Weight
             * @description Signed target weight in this live ranking (negative = short)
             */
            model_weight: number;
            /**
             * Plan Target Weight
             * @description Target weight in the latest frozen paper plan
             */
            plan_target_weight: number | null;
            /** Position Shares */
            position_shares: number;
            /** Current Weight */
            current_weight: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    data_quality_api_data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQuality"];
                };
            };
        };
    };
    imports_api_data_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataImport"][];
                };
            };
        };
    };
    refresh_api_data_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    universe_api_universe_get: {
        parameters: {
            query?: {
                /** @description Signal session (default: latest stored session) */
                session?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_detail_api_universe__symbol__get: {
        parameters: {
            query?: {
                session?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    command_center_api_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandCenter"];
                };
            };
        };
    };
    positions_api_portfolio_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsResponse"];
                };
            };
        };
    };
    paper_init_api_paper_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperInitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_advance_api_paper_advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperAdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_reset_api_paper_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    paper_config_api_paper_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperConfigResponse"];
                };
            };
        };
    };
    paper_config_update_api_paper_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reseed_demo_api_paper_seed_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    plans_api_rebalance_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
        };
    };
    current_api_rebalance_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetail"] | null;
                };
            };
        };
    };
    plan_detail_api_rebalance_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_api_rebalance_plans__plan_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_api_rebalance_plans__plan_id__skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    defaults_api_research_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchDefaults"];
                };
            };
        };
    };
    runs_api_research_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    launch_api_research_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_research_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_series_api_research_runs__run_id__series_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSeriesPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_monthly_api_research_runs__run_id__monthly_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReturn"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trades_api_research_runs__run_id__trades_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                symbol?: string | null;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_rebalances_api_research_runs__run_id__rebalances_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRebalance"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_api_ledger_orders_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fills_api_ledger_fills_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cash_api_ledger_cash_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_ledger_events_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                level?: string | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reproducibility_api_ledger_reproducibility_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reproducibility"];
                };
            };
        };
    };
}
